### ISSUE TITLE
Sync up with Prometheus style

### ISSUE THREAD

**Issue by brian-brazil** [caarlos0/promfmt#4]
It's great to have a tool to help with formatting, the style used however is not quite the standard Prometheus style. See https://prometheus.io/docs/practices/rules/ and https://prometheus.io/docs/alerting/rules/ for what it should look like.

**Comment by caarlos0** [comment]
@brian-brazil what exactly is out of sync? I don't see it... tabs vs spaces maybe?

**Comment by brian-brazil** [comment]
The by clause is after the expression rather than before, the {} on the LHS of rules is superfluous and there's too much indentation in the alerts (should be 2 spaces).

You should also check with more complex expressions, https://github.com/RobustPerception/demo_prometheus_ansible/blob/master/roles/prometheus/files/life.rules is well formatted for example.

**Comment by caarlos0** [comment]
@brian-brazil hmm, ok, I'll take a look :)

Thanks!
